# Draft Census Ward Report for Ward `r ward`
##### Report Date: `r Sys.Date()`

```{r setup, include=FALSE}
suppressWarnings(suppressPackageStartupMessages(library(ggplot2)))
suppressWarnings(suppressPackageStartupMessages(library(dplyr)))
suppressWarnings(suppressPackageStartupMessages(library(tmap)))
suppressWarnings(suppressPackageStartupMessages(library(sp)))
suppressWarnings(suppressPackageStartupMessages(library(sf)))
library(knitr)
library(markdown)
library(rmarkdown)

ward_tract_overlap <- gOverlaps(spgeom1 = shp_tracts, 
                         spgeom2 = shp_ward[shp_ward@data$ward == ward, ],
                         byid = TRUE)
ward_sf <- shp_tracts[which(ward_tract_overlap), ]
dt <- data.table(shp_tracts@data[ward_tract_overlap, ])

print(ward)
print(Sys.Date())

```

## Response Rate Map

```{r map, echo = FALSE}

plot(ward_sf)
plot(shp_ward[shp_ward@data$ward == ward, ], add = T, lwd = 3, border = "blue") 
```


## Data Table

```{r datatable, echo = FALSE}
dt[,
   j = list(Low_Response_Score = (100-mail_return_rate),
            Population_in_2010 = total_population,
            Black_percent = percent_population_black,
            Hispanic_percent = percent_population_hispanic,
            Mixed_Race_percent = percent_population_2_or_more_races
            ),
   by = "NAMELSAD"]
```