---
title: "Census 2020 Ward Level Results"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll #fill
    social: menu
    source_code: embed
runtime: shiny
---

```{r, include = FALSE}

## See: https://github.com/Chicago/census2020_ward_rpt/

geneorama::set_project_dir("census2020_ward_rpt")

# rm(list=ls())

library(shiny)
library(leaflet)
library(RColorBrewer)
library(colorspace)
library(rgdal) #for reading/writing geo files
library(rgeos) #for simplification
library(sp)
library(data.table)
library(plotly)
# library(tmap)
library(sf)
library(reactable)
library(tmap)
library(flexdashboard)

source("functions/sourceDir.R")
sourceDir("functions")

## LOAD CURRENT DATA AND CURRENT WARD
##*********************
##*********************
##*********************
load(max(list.files("WardReport_v2/cache", full.names = T)))
cur_ward <- yaml::read_yaml("WardReport_v2/cur_ward.yaml")
cur_ward <- cur_ward$cur_ward
##*********************
##*********************
##*********************

## Ward / tract crosswalk
ward_crosswalk <- fread("data_census_planning/crosswalk_replica_based.csv")
ward_crosswalk[ , tract := substr(TRACT, 6, 11)]

## Create data table for maps / summaries of all responses
resp_current$state <- NULL
resp_current$county <- NULL

resp_current <- merge(resp_current,
                      civis_pdb,
                      by.x = "TRACT",
                      by.y = "tract",
                      all.x = TRUE)
resp_current <- resp_current[!is.na(TRACT)]

## HTC instead?
htc[ , tract_2020 := substr(TRACT_2020, 6, 11)]
resp_current <- merge(resp_current,
                      htc[!is.na(TRACT_2020), MailReturnRateCen2010:tract_2020],
                      by.x = "TRACT",
                      by.y = "tract_2020",
                      all.x = TRUE)
# NAsummary(resp_current)
resp_current <- resp_current[!is.na(TRACT)]
# resp_current[!is.na(gidtr)]

## Calculate ward household table
resp_cur_ward <- merge(ward_crosswalk[ward == cur_ward,
                                      list(TRACT = tract,
                                           ward, 
                                           households_ward = households,
                                           households_tract = tract_total,
                                           allocation)], 
                       resp_current, 
                       by = "TRACT")

## Shape file of just current ward
shp_ward <- shp_wards[shp_wards$ward == cur_ward, ]
civis_ward_table <- civis_ward_table[match(shp_wards$ward, civis_ward_table$ward)]
civis_ward_table[ , LABEL := htmltools::HTML(hover_text), ward]

## Tract map of just this ward
## put data in same order as map
shp_ward_tract <- shp_tracts_2020[shp_tracts_2020@data$TRACT %in% resp_cur_ward$TRACT, ]
resp_cur_ward <- resp_cur_ward[match(shp_ward_tract@data$TRACT, resp_cur_ward$TRACT)]

## put data in same order as map
resp_current <- resp_current[match(shp_tracts_2020$TRACT, TRACT)]

## Map color definitions
cols_bright <- diverging_hcl(n = 7, h = c(360, 138), c = c(144, 42), 
                             l = c(67, 82), power = c(0.45, 1.1))
cols_muted <- diverging_hcl(n = 7, h = c(340, 128), c = c(60, 80), 
                            l = c(30, 97), power = c(0.8, 1.5))
cur_pal <- cols_muted

## City wide response
city_target_resp <- 75
city_cur_resp <- civis_ward_table[
  i = TRUE,
  j = sum(tot_occp_units_acs_13_17 * current_response_rate) / sum(tot_occp_units_acs_13_17)]
city_target_resp_civis <- civis_ward_table[
  i = TRUE,
  j = sum(tot_occp_units_acs_13_17 * civis_2020_target) / sum(tot_occp_units_acs_13_17)]
city_cur_resp <- round(city_cur_resp, 1)

## Ward specific respopnse numbers
ward_target_resp <- civis_ward_table[cur_ward, adjusted_civis_2020_target]
ward_cur_resp <- civis_ward_table[cur_ward, current_response_rate]
ward_target_resp_civis <- civis_ward_table[cur_ward, civis_2020_target]

## Household totals for value boxes
ward_hh_tot <- resp_cur_ward[ , sum(households_ward)]
ward_hh_resp_daily <- resp_cur_ward[ , round(sum(households_ward * DRRALL/100))]
ward_hh_resp_total <- resp_cur_ward[ , round(sum(households_ward * CRRALL/100))]

## Old way, see below for new way
## Create the ward-specific overlap files to be used in the making the map and table
# ii <- which(gOverlaps(spgeom1 = shp_tracts_2020,
#                       spgeom2 = shp_wards[shp_wards@data$ward == cur_ward, ],
#                       byid = TRUE)[1,])
# tracts_in_ward <- shp_tracts_2020@data[ii, "TRACT"]

## Merge civis and response data into census data
# shp_tracts_2020@data <- cbind(shp_tracts_2020@data,
#                               civis_pdb[match(shp_tracts_2020@data$TRACT, tract)],
#                               resp_current[match(shp_tracts_2020@data$TRACT, TRACT),
#                                            list(RESP_DATE, CRRALL,CRRINT)])
# lll()
# wtf(resp_cur_ward)
ward_labels <- 
  resp_cur_ward[i = TRUE, 
                j = list(LABEL = htmltools::HTML(
                  paste(paste0("Tract: ", TRACT),
                        paste0("As of ", RESP_DATE, " the response rate is ", 
                               CRRALL, "% overall."),
                        paste0("Households in tract: ",
                               prettyNum(households_tract, big.mark=",")),
                        paste0("Households in ward: ",
                               prettyNum(households_ward, big.mark=",")),
                        paste0("2010 mail return rate: ", mail_return_rate_cen_2010, "%"),
                        paste0("CB pred 2020 response:", 100-low_response_score, "%"),
                        paste0("Cur. total response", CRRALL, "%"),
                        paste0("Cur. total internet response:", CRRINT, "%"),
                        paste0("Total population 2010:", tot_population_cen_2010),
                        paste0("Black population 2010:", nh_blk_alone_acs_13_17),
                        paste0("Hisp. population 2010:", hispanic_acs_13_17),
                        paste0("Total population 2010:", tot_population_cen_2010),
                        paste0("Limited English Proficiency (LEP):", eng_vw_acs_13_17),
                        paste0("Single Parents:", HH_SingleParent),
                        sep = "<br>"))),
                  by = TRACT]
# str(ward_labels)
```


Row {data-height=120}
-------------------------------------

### Ward Total Gauge
```{r}
gauge(value = ward_cur_resp,
      label = "Ward",
      symbol = "%",
      min = 0, 
      max = 100, 
      gaugeSectors(success = c(ward_target_resp, 100), 
                   warning = c(ward_target_resp_civis, ward_target_resp), 
                   danger = c(0, ward_target_resp_civis)))
```

### City Total Gauge
```{r}
gauge(value = city_cur_resp,
      label = "City",
      symbol = "%",
      min = 0, 
      max = 100, 
      gaugeSectors(success = c(city_target_resp, 100), 
                   warning = c(city_target_resp-20, city_target_resp), 
                   danger = c(0, city_target_resp-20)))
```

### Ward
```{r}
valueBox(value =  prettyNum(ward_hh_tot, big.mark = ","), 
         caption = "total households",
         icon = "fa-pencil",
         color = "info")
```

### Ward
```{r}
valueBox(value = prettyNum(ward_hh_resp_daily, big.mark = ","), 
         caption = paste0("Responses for ", 
                          max(resp_current$RESP_DATE, na.rm=T)),
         icon = "fa-pencil",
         color = "info")
```

### Ward
```{r}
valueBox(value = prettyNum(ward_hh_resp_total, big.mark = ","), 
         caption = "Cumulative Responses",
         icon = "fa-pencil",
         color = "info")
```


Row {data-height=400}
-------------------------------------

### Daily results for Ward `r cur_ward`

```{r}
# output$daily_performance <- renderPlotly({
fig <- plot_ly(data = civis_daily_rates[!ward==cur_ward], 
               x = ~response_date, y = ~response_rate, 
               # color = ~ward,
               color = I("grey80"), name = "other wards",
               type = "scatter", mode="lines")
fig <- layout(fig,
              title = paste0("Cumulative Daily Response Rate\n Ward", cur_ward),
              xaxis = list(title = "Household % Responding"),
              yaxis = list (title = ""))
fig <- civis_daily_rates[ward==cur_ward, 
                         add_lines(fig, x=response_date, y=response_rate,
                                   name = paste("Ward", cur_ward),
                                   color = I("blue"))]
fig <- fig %>%
  layout(shapes = list(plotly_vline("2020-04-30", dash = "dash"), 
                       plotly_hline(ward_target_resp, dash = "dot", color = "green"),
                       plotly_hline(100, dash = "solid")),
         margin = list(t=80))
         # default margins:
         # margin = list(l = 80, r = 80, b = 80, t = 100, pad = 0)
fig <- add_text(fig, 
                x=as.IDate("2020-03-20"), 
                y = ward_target_resp + 5,
                text = "Goal response rate", color = I("gray20"), 
                showlegend = FALSE)
fig

# })
# plotlyOutput("daily_performance", width = "50%")
```

    
Row {.tabset .tabset-fade}
-------------------------------------

### Ward `r cur_ward`

```{r}
# output$wardmap <- renderLeaflet({
vec <- resp_cur_ward$CRRALL
pal <- colorNumeric(palette = cols_muted, domain = vec)
leaflet() %>%
  addProviderTiles("Stamen.TonerHybrid") %>% 
  addPolygons(data = shp_ward_tract,
              fillColor = ~ pal(vec),
              fillOpacity = 0.7, weight = 0.5,
              # label = ~ ward_spdf$TRACT,
              label = ~ ward_labels$LABEL) %>%
  addPolygons(data = shp_ward, fill = FALSE, color = "yellow", weight = 5, opacity = .75) %>%
  addPolygons(data = shp_ward, fill = FALSE, color = "blue", weight = 2, opacity = 1) %>%
  addLegend(pal = pal,
            values = vec,
            title = "% Resp Rate",
            position = "bottomright")
# })
# leafletOutput("wardmap", width = "50%", height = 400)
```

### Citywide performance

```{r}
vec <- civis_ward_table$current_response_rate
pal <- colorNumeric(palette = cur_pal, domain = vec)
leaflet() %>%
  addProviderTiles("Stamen.TonerHybrid") %>%
  addPolygons(data = shp_wards,
              fillColor = ~ pal(vec),
              fillOpacity = 0.7, weight = 0.5,
              label = ~civis_ward_table$LABEL) %>%
  addLegend(pal = pal,
            values = vec,
            title = "% Resp Rate",
            position = "bottomright")

# vec <- shp_tracts_2020$CRRALL
# pal <- colorNumeric(palette = cur_pal, domain = vec)
# leaflet() %>%
#   addProviderTiles("Stamen.TonerHybrid") %>%
#   addPolygons(data = shp_tracts_2020,
#               fillColor = ~ pal(vec),
#               fillOpacity = 0.7, weight = 0.5,
#               # label = ~ ward_spdf$TRACT,
#               label = ~ vec) %>%
#   addLegend(pal = pal,
#             values = vec,
#             title = "% Resp Rate",
#             position = "bottomright")
```

Row {data-height=650}
-------------------------------------

### Census tract demographics for Ward `r cur_ward`


```{r}
##------------------------------------------------------------------------------
## data table to show ward demographics - that will be saved as dt2
##------------------------------------------------------------------------------
# civis_pdb[match(tracts_in_ward, tract)]
# colnames(civis_pdb)
dt2 <- resp_cur_ward[i = TRUE,
                     j = list(low_response_score, tot_population_cen_2010, nh_blk_alone_acs_13_17, 
                              hispanic_acs_13_17, tot_housing_units_cen_2010, eng_vw_acs_13_17,
                              HH_SingleParent), 
                     by = list(TRACT)]

#add in percentages for specific columns
dt2[, c("perc_LEP", "perc_SP"):=list((eng_vw_acs_13_17/tot_housing_units_cen_2010*100), 
                                     (HH_SingleParent/tot_housing_units_cen_2010*100)), ]

#use the package Reactable to make the table fancy. 
#This requires creating a function for coloring purposes
YlOrRd <- function(x) rgb(colorRamp(c("#fff7ba", "#fee28a", "#fec05b", "#fd923e", "#fc502a", 
                                      "#df171c", "#b00026"))(x), 
                          maxColorValue = 255)

##------------------------------------------------------------------------------
## Reactable table
##------------------------------------------------------------------------------

stylefn <- function(value) {
  if (!is.numeric(value))
    return(min(civis_pdb$low_response_score,
               na.rm=TRUE))
  normalized <- (value -  min(civis_pdb$low_response_score, na.rm=TRUE)) /
    (max(civis_pdb$low_response_score, na.rm=TRUE) -
       min(civis_pdb$low_response_score, na.rm=TRUE))
  color <- ifelse(is.na(normalized),
                  "cyan",
                  YlOrRd(normalized))
  list(background = color)
}
rtable <- reactable(dt2, 
                    defaultColDef = colDef(align = "center",
                                           maxWidth = 70,
                                           headerStyle = list(background = "#f7f7f8")),
                    columns = list (TRACT = colDef(name = "Census Tract"),
                                    low_response_score = colDef(name = "Low Response Score", 
                                                                defaultSortOrder = "desc", 
                                                                style = stylefn),
                                    tot_population_cen_2010 = colDef(name = "Total"),
                                    nh_blk_alone_acs_13_17 = colDef(name = "Black"), 
                                    hispanic_acs_13_17 = colDef(name = "Hisp."),
                                    tot_housing_units_cen_2010 = colDef(name = "Total"),
                                    eng_vw_acs_13_17 = colDef(name = "Limited English Proficiency (LEP)"),
                                    perc_LEP = colDef(name = "% LEP", format = colFormat(digits = 2)),
                                    HH_SingleParent = colDef(name = "Single Parent"),
                                    perc_SP = colDef(name = "% Single Parent", 
                                                     format = colFormat(digits = 2))
                    ), 
                    columnGroups = list(colGroup(name = "Population", 
                                                 columns = c("tot_population_cen_2010", "nh_blk_alone_acs_13_17",
                                                             "hispanic_acs_13_17")),
                                        colGroup(name = "Households", 
                                                 columns = c("tot_housing_units_cen_2010",
                                                             "eng_vw_acs_13_17", 
                                                             "perc_LEP", "HH_SingleParent",
                                                             "perc_SP"))),
                    bordered = TRUE, resizable = TRUE, defaultSorted = "low_response_score")
rtable
```


```{r, include = FALSE}
## Rank Table

# output$ward_demographics <- renderReactable({rtable})
# reactableOutput("ward_demographics")

# #Next, use Reactable to come up with a rank table that highlights the specific position
# #the ward has in comparison to other wards. 
# rowfn <- function(index) {
#   a <- which(rankdt$ward == ward)
#   if (index == a) list(background = "rgba(252, 140, 140, 0.5)")
# }
# ranktable <- reactable(rankdt, 
#                        columns = list(ward = colDef(name = "Ward", format = colFormat(digits = 0)),
#                                       mean_response = colDef(name = "Raw Response Rate (%)"),
#                                       mean_handicap = colDef(name = "Weighting Factor"),
#                                       mean_weightedresponse = colDef(name = "Weighted Response Rate (%)",
#                                                                      defaultSortOrder = "desc")
#                        ), 
# rowStyle = rowfn, 
# bordered = TRUE, resizable = TRUE, defaultSorted = "mean_weightedresponse", defaultColDef = colDef(format = colFormat(digits = 2))
# )
# 
# #Last, display the ranking as a raw number
# ranking <- rankings[rankdt$ward==ward]
# ranking <- 50 - ranking
```



```{r, include=FALSE}

## TMAP VERSION NOT WORKING BECAUSE IT WON'T RENDER IN DASHBOARD

# ## Create the ward-specific overlap files to be used in the making the map and table
# ii <- which(gOverlaps(spgeom1 = shp_tracts_2020, 
#                       spgeom2 = shp_wards[shp_wards@data$ward == cur_ward, ],
#                       byid = TRUE)[1,])
# tracts_in_ward <- shp_tracts_2020@data[ii, "TRACT"]
# 
# ## Subset map to ward
# ward_spdf <- shp_tracts_2020[ii, ]
# head(ward_spdf@data)
# 
# #convert file to tmap format
# ward_sf <- st_as_sf(ward_spdf, crs = 4326)
# 
# ##------------------------------------------------------------------------------
# ## Ward map based on Civis planning database
# ##------------------------------------------------------------------------------
# #start by defining variables that will pop up and breaks
# popups <- c("tract", "low_response_score", "tot_population_cen_2010",
#             "tot_housing_units_cen_2010", "nh_blk_alone_acs_13_17",
#             "hispanic_acs_13_17", "eng_vw_acs_13_17"
#             # , "HH_SingleParent"
#             )
# breaks <- seq(0, 45, by = 5)
# 
# popups%in% colnames(ward_spdf@data)
# 
# #this will actually make the map
# map1 <- tm_shape(ward_sf, is.master = TRUE) +
#   tm_polygons(col = "low_response_score", palette = c("#FFFFFF","#22556F"),
#               style="cont", alpha = .7, title = "Low       Response Score",
#               breaks=breaks, popup.var = popups,
#               group = "Relevant Ward Census Tracts") +
#   tm_layout(title = "Heatmap of Low Response Scores") +
#   tm_view(view.legend.position = c("left", "bottom"))  +
#   tm_basemap(server = "OpenMapSurfer.Roads") +
#   tm_shape(ward_spdf) +
#   tm_borders(col = "black", lwd=3, group = paste0("Ward ", cur_ward, " Outline"))
# # current.mode <- tmap_mode(c("plot", "view")[2])
# tmap_leaflet(map1)
```

